spring:
  liquibase:
    change-log: classpath:db/changelog/master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/habits
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
